use anyhow::Result;
use std::io::{self, Write};

mod extractor;
mod inserter;
mod reader;

use extractor::extract_summaries;
use inserter::insert_summaries;
use reader::{read_file, read_input};

/// Expect CHANGELOG.md contains sections of `### Summary`, with certain contents.
/// Expect stdin is the CHANGELOG generated by git-cliff, which does not contains sections of `### Summary`.
/// Extract the `### Summary` sections from CHANGELOG.md into the newly generated CHANGELOG, and print the result to
/// stdout.
///
/// Example use case:
///
/// ```shell
/// git-cliff | preserve-summaries
/// ```
fn main() -> Result<()> {
    let file = read_file()?;
    let version_to_summary = extract_summaries(&file);

    let input = read_input()?;
    let output = insert_summaries(&input, &version_to_summary);

    io::stdout().write_all(output.as_bytes())?;

    Ok(())
}
