use std::fs::File;
use std::io::{self, Read, Write};

use anyhow::{Context, Result};

mod extractor;
mod inserter;
mod reader;

use extractor::extract_summaries;
use inserter::insert_summaries;

/// Expect CHANGELOG.md contains sections of `### Summary`, with certain contents.
/// Expect stdin is the CHANGELOG generated by git-cliff, which does not contains sections of `### Summary`.
/// Extract the `### Summary` sections from CHANGELOG.md into the newly generated CHANGELOG, and print the result to
/// stdout.
///
/// Example use case:
///
/// ```shell
/// git-cliff | preserve-summaries
/// ```
fn main() -> Result<()> {
    let file = read_file()?;
    let version_to_summary = extract_summaries(&file)?;

    let input = read_input()?;
    let output = insert_summaries(&input, &version_to_summary)?;

    io::stdout().write_all(output.as_bytes())?;

    Ok(())
}

/// Read content from `CHANGELOG.md`.
pub fn read_file() -> Result<String> {
    let mut f = File::open("CHANGELOG.md").context("failed to open CHANGELOG.md")?;
    let mut buf = String::new();

    f.read_to_string(&mut buf)?;

    Ok(buf)
}

/// Read content from STDIN.
pub fn read_input() -> Result<String> {
    let mut stdin = io::stdin();
    let mut buf = String::new();

    stdin.read_to_string(&mut buf)?;

    Ok(buf)
}
